status and logging
StochSS/stochss-compute pull request #160
Opened 2022-11-01 23:53 UTC by mdip226

added logfile parameter and changed prints to logging.info()

2022-11-07 21:20 UTC, BryanRumsey requested changes
- Need to setup a stochss compute logger.
- Need additional status updates.

2022-11-09 16:44 UTC, mdip226 commented
rename EC2Cluster

2022-11-16 03:23 UTC, BryanRumsey approved these changes

2022-11-16 17:15 UTC, briandrawert commented on stochss_compute/cloud/ec2.py
> +    def __init__(self, statusFile=None) -> None:
To conform with Python standards, we should use 'snake case' not 'camel case' where we can.  Please change this to "status_file"

2022-11-16 17:15 UTC, briandrawert commented on stochss_compute/cloud/ec2.py
> +        :param statusFile: Optional. If provided, status updates will be written to a file with this path and name.
and here

2022-11-16 17:15 UTC, briandrawert commented on stochss_compute/cloud/ec2.py
> +        self.statusFile = statusFile
and here

2022-11-16 17:15 UTC, briandrawert commented on stochss_compute/cloud/ec2.py
> +        if self.statusFile is not None:
and here

2022-11-23 15:47 UTC, mdip226 commented
> This might not be the right place to discuss, but a "sssc-root.pem" file is being created. This should be configured to be in a different location. Ask @BryanRumsey for more info

I'm gonna work on that in #164 that way I can organize the changes into one chunk. Basically I'm gonna pull out the constants from the ec2 file and make them configurable.

2022-12-05 15:38 UTC, BryanRumsey approved these changes

2022-12-08 22:23 UTC, briandrawert approved these changes

2022-12-08 22:23 UTC, merged