0.9.9
StochSS/stochss-compute pull request #169
Opened 2023-01-10 22:28 UTC by mdip226

code freeze!
TODO:
- [ ] Sphinx Docs #126 
- [ ] double check #152 
- [ ] #149 
- [ ] double check #150 
- [ ] #165
- [ ] #159 
- [ ] ...
- [ ] readme, etc.

2023-01-31 18:15 UTC, briandrawert approved these changes

2023-02-06 18:00 UTC, BryanRumsey requested changes
The test structure is incorrect

2023-02-06 18:00 UTC, BryanRumsey commented on stochss_compute/server/sourceip.py
> +        :returns: request.remote_ip
Return doc should be a brief description of what is returned.  Missing return type in docs.

2023-02-07 22:40 UTC, mdip226 commented on stochss_compute/cloud/ec2.py
> +            # os.makedirs(self._local_config.status_file, exist_ok=True)
- [x]

2023-02-07 22:47 UTC, mdip226 commented on stochss_compute/cloud/ec2.py
> +            if rtb.associations_attribute[0]['Main'] is True:
I believe that `is True` is right because it is checking for the actual value `True`.

2023-02-07 22:48 UTC, mdip226 commented on stochss_compute/cloud/ec2.py
> +            if rtb.associations_attribute[0]['Main'] is True:
The left side is a boto3 ec2 RouteTable resource handle object

2023-02-07 22:50 UTC, mdip226 commented on stochss_compute/server/cache.py
> +        :type None:
- [x] -

2023-02-08 16:37 UTC, mdip226 commented
Ready to Merge<sup>TM</sup>

2023-02-08 17:01 UTC, BryanRumsey approved these changes

2023-02-09 16:46 UTC, seanebum approved these changes

2023-02-09 18:58 UTC, merged