fix missing underscore
StochSS/stochss-compute pull request #175
Opened 2023-02-17 23:13 UTC by mdip226

2023-02-21 21:22 UTC, BryanRumsey approved these changes

2023-02-21 21:27 UTC, briandrawert requested changes

2023-02-21 21:27 UTC, briandrawert commented on stochss_compute/server/status.py
> +    scheduler_address = None
These initialization should be moved to a Constructor function.

2023-02-21 21:34 UTC, mdip226 commented on stochss_compute/server/status.py
> +    scheduler_address = None
Ok yeah that'll work

2023-02-23 02:35 UTC, briandrawert approved these changes

2023-02-23 02:35 UTC, merged