Fix/results type error
StochSS/stochss-compute pull request #31
Opened 2021-10-28 13:05 UTC by mdip226

:)

2021-10-31 18:27 UTC, ethangreen-dev requested changes
Needs a couple changes / clarifications. Otherwise it looks good! :)

2021-10-31 18:27 UTC, ethangreen-dev commented on requirements.txt
> +pandas
What's the need for these additional dependencies?

2021-10-31 18:27 UTC, ethangreen-dev commented on stochss_compute/api/v1/memory.py
> +    memory: Results = Jsonify.from_json(delegate.job_results(memory_id))
I'm not sure if 
`Jsonify#from_json` will deserialize the JSON to the right type. Better to be explicit and use `Results#from_json`.

2021-11-04 15:29 UTC, mdip226 commented on stochss_compute/api/v1/memory.py
> +    memory: Results = Jsonify.from_json(delegate.job_results(memory_id))
ah, yeah

2021-11-05 16:41 UTC, mdip226 commented on requirements.txt
> +pandas
ok, I am now relatively sure that the only one of these that we need is blosc. For the error that it fixes, refer to this
[logs-from-stochss-compute-in-stochss-compute-6cff5f86df-6p4qf.txt](https://github.com/StochSS/stochss-compute/files/7487581/logs-from-stochss-compute-in-stochss-compute-6cff5f86df-6p4qf.txt)

2021-11-05 16:45 UTC, mdip226 commented on requirements.txt
> +pandas
But to answer your question, I don't know. It seems weird to me that this package was not already included in one of the other dask packages

2021-11-06 16:45 UTC, ethangreen-dev approved these changes

2021-11-06 16:45 UTC, merged