Docs/readme
StochSS/stochss-compute pull request #40
Opened 2021-11-11 13:41 UTC by mdip226

2021-11-20 18:56 UTC, briandrawert commented
I was not able to successfully follow the readme.  See #47

2021-11-21 20:31 UTC, ethangreen-dev requested changes
Fantastic work so far, just needs a couple additions / changes and it'll be perfect.

2021-11-21 20:31 UTC, ethangreen-dev commented on README.md
> +can easily save and recall previous simulations.
I would replace this with something for generic (as GillesPy2 is just the start). Maybe something like this "A distributed compute delegation server for the StochSS family of stochastic simulators."?

2021-11-21 20:31 UTC, ethangreen-dev commented on README.md
> +
We should probably add two sections: How to set Dask up, and how to best configure stochss-compute. We can chat strategies about the latter.

2021-11-21 20:31 UTC, ethangreen-dev commented on README.md
> +results.wait()
`results.wait()` will wait for the job to finish (but not get the results), `results.resolve()` will wait for the job to complete and grab the results from the server.

2021-11-21 20:31 UTC, ethangreen-dev commented on stochss_compute/api/delegate/dask_delegate.py
> +                self.client = Client()
Revert this change. Issue [#47](https://github.com/StochSS/stochss-compute/issues/47) was fixed with PR #49.

2021-11-21 21:02 UTC, mdip226 commented on README.md
> +
I agree, def

2021-11-21 21:05 UTC, mdip226 commented on README.md
> +can easily save and recall previous simulations.
I was gonna do that but then I just figured to wait until that's fully implemented

2021-11-21 21:10 UTC, mdip226 commented on README.md
> +can easily save and recall previous simulations.
but yeah, i agree with what you said

2021-11-21 21:11 UTC, mdip226 commented on README.md
> +results.wait()
ah, gotcha.

2021-12-10 19:56 UTC, mdip226 commented on README.md
> +
I'm just going to make a separate notebook for this

2021-12-14 19:54 UTC, briandrawert requested changes
When I walked through the README, I got the error in #58

2021-12-20 18:05 UTC, briandrawert commented
Merge #52 before merging this PR

2022-01-22 17:33 UTC, briandrawert approved these changes

2022-01-22 17:33 UTC, merged