Mdip/feature/46 use GitHub actions to automate docker images pushes Closes #46
StochSS/stochss-compute pull request #93
Opened 2022-03-21 14:12 UTC by mdip226

2022-04-08 19:29 UTC, ethangreen-dev commented on app.py
> +        port = 29681
This has already been set in `develop`.

2022-04-15 19:49 UTC, ethangreen-dev requested changes
Looks good!

2022-04-15 19:49 UTC, ethangreen-dev commented on stochss_compute/api/delegate/dask_delegate.py
> +                print(self.client)
Debug prints need to be removed.

2022-04-15 19:49 UTC, ethangreen-dev commented on stochss_compute/compute_server.py
> +                print(ce.strerror)
Same here!

2022-04-15 19:53 UTC, briandrawert approved these changes

2022-04-16 01:00 UTC, mdip226 commented on stochss_compute/compute_server.py
> +                print(ce.strerror)
lol I thought I got those earlier

2022-04-16 01:03 UTC, mdip226 commented
I think that's it!

2022-05-16 18:25 UTC, briandrawert approved these changes

2022-05-16 18:26 UTC, ethangreen-dev approved these changes
Looks good!

2022-05-16 18:26 UTC, merged